apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: eso-cftc
spec:
 secretStoreRef:
   name: aws-parameter-store
   kind: SecretStore
 target:
   name: eso-cftc
 data:
 - secretKey: password
   remoteRef:
     key: eso-cftc
     property: secret.password