apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
 name: push-secret
 namespace: default
spec:
 refreshInterval: 10s
 secretStoreRefs:
   - name: aws-secrets-manager
     kind: SecretStore
 selector:
   secret:
     name: eso-cftc
 data:
   - match:
       secretKey: password
       remoteRef:
         remoteKey: eso-cftc